name: Functional tests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOLOKA_TOKEN: ${{ secrets.TOLOKA_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Run tox with Python 3.8
      id: tests
      run: |
        python -m tox -e py38-functional-tests
